/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * An ASP.NET Core Web API for managing ToDo items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTeamResponse
 */
export interface AddTeamResponse {
    /**
     * 
     * @type {number}
     * @memberof AddTeamResponse
     */
    teamId?: number;
}

/**
 * Check if a given object implements the AddTeamResponse interface.
 */
export function instanceOfAddTeamResponse(value: object): boolean {
    return true;
}

export function AddTeamResponseFromJSON(json: any): AddTeamResponse {
    return AddTeamResponseFromJSONTyped(json, false);
}

export function AddTeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTeamResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
    };
}

export function AddTeamResponseToJSON(value?: AddTeamResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teamId': value['teamId'],
    };
}

