/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * An ASP.NET Core Web API for managing ToDo items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AddTeamCommand
 */
export interface AddTeamCommand {
    /**
     * 
     * @type {string}
     * @memberof AddTeamCommand
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AddTeamCommand
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof AddTeamCommand
     */
    userId?: number;
}

/**
 * Check if a given object implements the AddTeamCommand interface.
 */
export function instanceOfAddTeamCommand(value: object): boolean {
    return true;
}

export function AddTeamCommandFromJSON(json: any): AddTeamCommand {
    return AddTeamCommandFromJSONTyped(json, false);
}

export function AddTeamCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddTeamCommand {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function AddTeamCommandToJSON(value?: AddTeamCommand | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'userId': value['userId'],
    };
}

