/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateOrganizationResponse } from './CreateOrganizationResponse';
import {
    CreateOrganizationResponseFromJSON,
    CreateOrganizationResponseFromJSONTyped,
    CreateOrganizationResponseToJSON,
} from './CreateOrganizationResponse';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';

/**
 * 
 * @export
 * @interface CreateOrganizationResponseQzResponse
 */
export interface CreateOrganizationResponseQzResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateOrganizationResponseQzResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof CreateOrganizationResponseQzResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {CreateOrganizationResponse}
     * @memberof CreateOrganizationResponseQzResponse
     */
    data?: CreateOrganizationResponse;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationResponseQzResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationResponseQzResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the CreateOrganizationResponseQzResponse interface.
 */
export function instanceOfCreateOrganizationResponseQzResponse(value: object): boolean {
    return true;
}

export function CreateOrganizationResponseQzResponseFromJSON(json: any): CreateOrganizationResponseQzResponse {
    return CreateOrganizationResponseQzResponseFromJSONTyped(json, false);
}

export function CreateOrganizationResponseQzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationResponseQzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CreateOrganizationResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function CreateOrganizationResponseQzResponseToJSON(value?: CreateOrganizationResponseQzResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': CreateOrganizationResponseToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

