/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrganizationResponse
 */
export interface CreateOrganizationResponse {
    /**
     * 
     * @type {string}
     * @memberof CreateOrganizationResponse
     */
    teamId?: string;
}

/**
 * Check if a given object implements the CreateOrganizationResponse interface.
 */
export function instanceOfCreateOrganizationResponse(value: object): boolean {
    return true;
}

export function CreateOrganizationResponseFromJSON(json: any): CreateOrganizationResponse {
    return CreateOrganizationResponseFromJSONTyped(json, false);
}

export function CreateOrganizationResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganizationResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
    };
}

export function CreateOrganizationResponseToJSON(value?: CreateOrganizationResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teamId': value['teamId'],
    };
}

