/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateProjectResponse } from './CreateProjectResponse';
import {
    CreateProjectResponseFromJSON,
    CreateProjectResponseFromJSONTyped,
    CreateProjectResponseToJSON,
} from './CreateProjectResponse';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';

/**
 * 
 * @export
 * @interface CreateProjectResponseQzResponse
 */
export interface CreateProjectResponseQzResponse {
    /**
     * 
     * @type {boolean}
     * @memberof CreateProjectResponseQzResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof CreateProjectResponseQzResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {CreateProjectResponse}
     * @memberof CreateProjectResponseQzResponse
     */
    data?: CreateProjectResponse;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectResponseQzResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateProjectResponseQzResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the CreateProjectResponseQzResponse interface.
 */
export function instanceOfCreateProjectResponseQzResponse(value: object): boolean {
    return true;
}

export function CreateProjectResponseQzResponseFromJSON(json: any): CreateProjectResponseQzResponse {
    return CreateProjectResponseQzResponseFromJSONTyped(json, false);
}

export function CreateProjectResponseQzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateProjectResponseQzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : CreateProjectResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function CreateProjectResponseQzResponseToJSON(value?: CreateProjectResponseQzResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': CreateProjectResponseToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

