/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListProjectRequest
 */
export interface ListProjectRequest {
    /**
     * 
     * @type {string}
     * @memberof ListProjectRequest
     */
    organizationId?: string;
}

/**
 * Check if a given object implements the ListProjectRequest interface.
 */
export function instanceOfListProjectRequest(value: object): boolean {
    return true;
}

export function ListProjectRequestFromJSON(json: any): ListProjectRequest {
    return ListProjectRequestFromJSONTyped(json, false);
}

export function ListProjectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListProjectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'organizationId': json['organizationId'] == null ? undefined : json['organizationId'],
    };
}

export function ListProjectRequestToJSON(value?: ListProjectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'organizationId': value['organizationId'],
    };
}

