/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Organization } from './Organization';
import {
    OrganizationFromJSON,
    OrganizationFromJSONTyped,
    OrganizationToJSON,
} from './Organization';

/**
 * 
 * @export
 * @interface ListOrgResponse
 */
export interface ListOrgResponse {
    /**
     * 
     * @type {Array<Organization>}
     * @memberof ListOrgResponse
     */
    orgs?: Array<Organization>;
}

/**
 * Check if a given object implements the ListOrgResponse interface.
 */
export function instanceOfListOrgResponse(value: object): boolean {
    return true;
}

export function ListOrgResponseFromJSON(json: any): ListOrgResponse {
    return ListOrgResponseFromJSONTyped(json, false);
}

export function ListOrgResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrgResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'orgs': json['orgs'] == null ? undefined : ((json['orgs'] as Array<any>).map(OrganizationFromJSON)),
    };
}

export function ListOrgResponseToJSON(value?: ListOrgResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'orgs': value['orgs'] == null ? undefined : ((value['orgs'] as Array<any>).map(OrganizationToJSON)),
    };
}

