/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { ListOrgResponse } from './ListOrgResponse';
import {
    ListOrgResponseFromJSON,
    ListOrgResponseFromJSONTyped,
    ListOrgResponseToJSON,
} from './ListOrgResponse';

/**
 * 
 * @export
 * @interface ListOrgResponseQzResponse
 */
export interface ListOrgResponseQzResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ListOrgResponseQzResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof ListOrgResponseQzResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {ListOrgResponse}
     * @memberof ListOrgResponseQzResponse
     */
    data?: ListOrgResponse;
    /**
     * 
     * @type {string}
     * @memberof ListOrgResponseQzResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ListOrgResponseQzResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the ListOrgResponseQzResponse interface.
 */
export function instanceOfListOrgResponseQzResponse(value: object): boolean {
    return true;
}

export function ListOrgResponseQzResponseFromJSON(json: any): ListOrgResponseQzResponse {
    return ListOrgResponseQzResponseFromJSONTyped(json, false);
}

export function ListOrgResponseQzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListOrgResponseQzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : ListOrgResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function ListOrgResponseQzResponseToJSON(value?: ListOrgResponseQzResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': ListOrgResponseToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

