/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ListMembersResponse2
 */
export interface ListMembersResponse2 {
    /**
     * 
     * @type {string}
     * @memberof ListMembersResponse2
     */
    teamId?: string;
}

/**
 * Check if a given object implements the ListMembersResponse2 interface.
 */
export function instanceOfListMembersResponse2(value: object): boolean {
    return true;
}

export function ListMembersResponse2FromJSON(json: any): ListMembersResponse2 {
    return ListMembersResponse2FromJSONTyped(json, false);
}

export function ListMembersResponse2FromJSONTyped(json: any, ignoreDiscriminator: boolean): ListMembersResponse2 {
    if (json == null) {
        return json;
    }
    return {
        
        'teamId': json['teamId'] == null ? undefined : json['teamId'],
    };
}

export function ListMembersResponse2ToJSON(value?: ListMembersResponse2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'teamId': value['teamId'],
    };
}

