/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { LoginResponse } from './LoginResponse';
import {
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
} from './LoginResponse';

/**
 * 
 * @export
 * @interface LoginResponseQzResponse
 */
export interface LoginResponseQzResponse {
    /**
     * 
     * @type {boolean}
     * @memberof LoginResponseQzResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof LoginResponseQzResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {LoginResponse}
     * @memberof LoginResponseQzResponse
     */
    data?: LoginResponse;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseQzResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof LoginResponseQzResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the LoginResponseQzResponse interface.
 */
export function instanceOfLoginResponseQzResponse(value: object): boolean {
    return true;
}

export function LoginResponseQzResponseFromJSON(json: any): LoginResponseQzResponse {
    return LoginResponseQzResponseFromJSONTyped(json, false);
}

export function LoginResponseQzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginResponseQzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : LoginResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function LoginResponseQzResponseToJSON(value?: LoginResponseQzResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': LoginResponseToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

