/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';

/**
 * 
 * @export
 * @interface MemberResponseQzResponse
 */
export interface MemberResponseQzResponse {
    /**
     * 
     * @type {boolean}
     * @memberof MemberResponseQzResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof MemberResponseQzResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {object}
     * @memberof MemberResponseQzResponse
     */
    data?: object;
    /**
     * 
     * @type {string}
     * @memberof MemberResponseQzResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof MemberResponseQzResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the MemberResponseQzResponse interface.
 */
export function instanceOfMemberResponseQzResponse(value: object): boolean {
    return true;
}

export function MemberResponseQzResponseFromJSON(json: any): MemberResponseQzResponse {
    return MemberResponseQzResponseFromJSONTyped(json, false);
}

export function MemberResponseQzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberResponseQzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : json['data'],
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function MemberResponseQzResponseToJSON(value?: MemberResponseQzResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': value['data'],
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

