/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Workitem } from './Workitem';
import {
    WorkitemFromJSON,
    WorkitemFromJSONTyped,
    WorkitemToJSON,
} from './Workitem';

/**
 * 
 * @export
 * @interface MyIssueResponse
 */
export interface MyIssueResponse {
    /**
     * 
     * @type {Array<Workitem>}
     * @memberof MyIssueResponse
     */
    readonly issues?: Array<Workitem>;
}

/**
 * Check if a given object implements the MyIssueResponse interface.
 */
export function instanceOfMyIssueResponse(value: object): boolean {
    return true;
}

export function MyIssueResponseFromJSON(json: any): MyIssueResponse {
    return MyIssueResponseFromJSONTyped(json, false);
}

export function MyIssueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyIssueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'issues': json['issues'] == null ? undefined : ((json['issues'] as Array<any>).map(WorkitemFromJSON)),
    };
}

export function MyIssueResponseToJSON(value?: Omit<MyIssueResponse, 'issues'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
    };
}

