/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Issue } from './Issue';
import {
    IssueFromJSON,
    IssueFromJSONTyped,
    IssueToJSON,
} from './Issue';

/**
 * 
 * @export
 * @interface MyIssueResponse
 */
export interface MyIssueResponse {
    /**
     * 
     * @type {Array<Issue>}
     * @memberof MyIssueResponse
     */
    issues?: Array<Issue>;
}

/**
 * Check if a given object implements the MyIssueResponse interface.
 */
export function instanceOfMyIssueResponse(value: object): boolean {
    return true;
}

export function MyIssueResponseFromJSON(json: any): MyIssueResponse {
    return MyIssueResponseFromJSONTyped(json, false);
}

export function MyIssueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MyIssueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'issues': json['issues'] == null ? undefined : ((json['issues'] as Array<any>).map(IssueFromJSON)),
    };
}

export function MyIssueResponseToJSON(value?: MyIssueResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'issues': value['issues'] == null ? undefined : ((value['issues'] as Array<any>).map(IssueToJSON)),
    };
}

