/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * An ASP.NET Core Web API for managing ToDo items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Org
 */
export interface Org {
    /**
     * 
     * @type {number}
     * @memberof Org
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof Org
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Org
     */
    describe?: string;
    /**
     * 
     * @type {Date}
     * @memberof Org
     */
    createdTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof Org
     */
    createUserId?: number;
}

/**
 * Check if a given object implements the Org interface.
 */
export function instanceOfOrg(value: object): boolean {
    return true;
}

export function OrgFromJSON(json: any): Org {
    return OrgFromJSONTyped(json, false);
}

export function OrgFromJSONTyped(json: any, ignoreDiscriminator: boolean): Org {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'describe': json['describe'] == null ? undefined : json['describe'],
        'createdTime': json['createdTime'] == null ? undefined : (new Date(json['createdTime'])),
        'createUserId': json['createUserId'] == null ? undefined : json['createUserId'],
    };
}

export function OrgToJSON(value?: Org | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'describe': value['describe'],
        'createdTime': value['createdTime'] == null ? undefined : ((value['createdTime']).toISOString()),
        'createUserId': value['createUserId'],
    };
}

