/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Project
 */
export interface Project {
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    projectName?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    describe?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Project
     */
    createdBy?: string;
}

/**
 * Check if a given object implements the Project interface.
 */
export function instanceOfProject(value: object): boolean {
    return true;
}

export function ProjectFromJSON(json: any): Project {
    return ProjectFromJSONTyped(json, false);
}

export function ProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): Project {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'projectName': json['projectName'] == null ? undefined : json['projectName'],
        'describe': json['describe'] == null ? undefined : json['describe'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
    };
}

export function ProjectToJSON(value?: Project | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'orgId': value['orgId'],
        'projectName': value['projectName'],
        'describe': value['describe'],
        'createdAt': value['createdAt'],
        'createdBy': value['createdBy'],
    };
}

