/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * An ASP.NET Core Web API for managing ToDo items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TodoItemResponse } from './TodoItemResponse';
import {
    instanceOfTodoItemResponse,
    TodoItemResponseFromJSON,
    TodoItemResponseFromJSONTyped,
    TodoItemResponseToJSON,
} from './TodoItemResponse';

/**
 * @type QzResponseOfTodoItemResponseData
 * 
 * @export
 */
export type QzResponseOfTodoItemResponseData = TodoItemResponse;

export function QzResponseOfTodoItemResponseDataFromJSON(json: any): QzResponseOfTodoItemResponseData {
    return QzResponseOfTodoItemResponseDataFromJSONTyped(json, false);
}

export function QzResponseOfTodoItemResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfTodoItemResponseData {
    if (json == null) {
        return json;
    }
    return TodoItemResponseFromJSONTyped(json, true);
}

export function QzResponseOfTodoItemResponseDataToJSON(value?: QzResponseOfTodoItemResponseData | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTodoItemResponse(value)) {
        return TodoItemResponseToJSON(value as TodoItemResponse);
    }

    return {};
}

