/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type QzResponseOfListMembersResponseData
 * 
 * @export
 */
export type QzResponseOfListMembersResponseData = object;

export function QzResponseOfListMembersResponseDataFromJSON(json: any): QzResponseOfListMembersResponseData {
    return QzResponseOfListMembersResponseDataFromJSONTyped(json, false);
}

export function QzResponseOfListMembersResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfListMembersResponseData {
    if (json == null) {
        return json;
    }
    return objectFromJSONTyped(json, true);
}

export function QzResponseOfListMembersResponseDataToJSON(value?: QzResponseOfListMembersResponseData | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfobject(value)) {
        return objectToJSON(value as object);
    }

    return {};
}

