/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { QzResponseOfMemberResponseData } from './QzResponseOfMemberResponseData';
import {
    QzResponseOfMemberResponseDataFromJSON,
    QzResponseOfMemberResponseDataFromJSONTyped,
    QzResponseOfMemberResponseDataToJSON,
} from './QzResponseOfMemberResponseData';

/**
 * 
 * @export
 * @interface QzResponseOfMemberResponse
 */
export interface QzResponseOfMemberResponse {
    /**
     * 
     * @type {boolean}
     * @memberof QzResponseOfMemberResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof QzResponseOfMemberResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {QzResponseOfMemberResponseData}
     * @memberof QzResponseOfMemberResponse
     */
    data?: QzResponseOfMemberResponseData;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfMemberResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfMemberResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the QzResponseOfMemberResponse interface.
 */
export function instanceOfQzResponseOfMemberResponse(value: object): boolean {
    return true;
}

export function QzResponseOfMemberResponseFromJSON(json: any): QzResponseOfMemberResponse {
    return QzResponseOfMemberResponseFromJSONTyped(json, false);
}

export function QzResponseOfMemberResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfMemberResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : QzResponseOfMemberResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function QzResponseOfMemberResponseToJSON(value?: QzResponseOfMemberResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': QzResponseOfMemberResponseDataToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

