/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { LoginResponse } from './LoginResponse';
import {
    instanceOfLoginResponse,
    LoginResponseFromJSON,
    LoginResponseFromJSONTyped,
    LoginResponseToJSON,
} from './LoginResponse';

/**
 * @type QzResponseOfLoginResponseData
 * 
 * @export
 */
export type QzResponseOfLoginResponseData = LoginResponse;

export function QzResponseOfLoginResponseDataFromJSON(json: any): QzResponseOfLoginResponseData {
    return QzResponseOfLoginResponseDataFromJSONTyped(json, false);
}

export function QzResponseOfLoginResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfLoginResponseData {
    if (json == null) {
        return json;
    }
    return LoginResponseFromJSONTyped(json, true);
}

export function QzResponseOfLoginResponseDataToJSON(value?: QzResponseOfLoginResponseData | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfLoginResponse(value)) {
        return LoginResponseToJSON(value as LoginResponse);
    }

    return {};
}

