/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { ListMembersResponse2 } from './ListMembersResponse2';
import {
    instanceOfListMembersResponse2,
    ListMembersResponse2FromJSON,
    ListMembersResponse2FromJSONTyped,
    ListMembersResponse2ToJSON,
} from './ListMembersResponse2';

/**
 * @type QzResponseOfListMembersResponse2Data
 * 
 * @export
 */
export type QzResponseOfListMembersResponse2Data = ListMembersResponse2;

export function QzResponseOfListMembersResponse2DataFromJSON(json: any): QzResponseOfListMembersResponse2Data {
    return QzResponseOfListMembersResponse2DataFromJSONTyped(json, false);
}

export function QzResponseOfListMembersResponse2DataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfListMembersResponse2Data {
    if (json == null) {
        return json;
    }
    return ListMembersResponse2FromJSONTyped(json, true);
}

export function QzResponseOfListMembersResponse2DataToJSON(value?: QzResponseOfListMembersResponse2Data | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfListMembersResponse2(value)) {
        return ListMembersResponse2ToJSON(value as ListMembersResponse2);
    }

    return {};
}

