/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { QzResponseOfListOrgResponseData } from './QzResponseOfListOrgResponseData';
import {
    QzResponseOfListOrgResponseDataFromJSON,
    QzResponseOfListOrgResponseDataFromJSONTyped,
    QzResponseOfListOrgResponseDataToJSON,
} from './QzResponseOfListOrgResponseData';

/**
 * 
 * @export
 * @interface QzResponseOfListOrgResponse
 */
export interface QzResponseOfListOrgResponse {
    /**
     * 
     * @type {boolean}
     * @memberof QzResponseOfListOrgResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof QzResponseOfListOrgResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {QzResponseOfListOrgResponseData}
     * @memberof QzResponseOfListOrgResponse
     */
    data?: QzResponseOfListOrgResponseData;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfListOrgResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfListOrgResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the QzResponseOfListOrgResponse interface.
 */
export function instanceOfQzResponseOfListOrgResponse(value: object): boolean {
    return true;
}

export function QzResponseOfListOrgResponseFromJSON(json: any): QzResponseOfListOrgResponse {
    return QzResponseOfListOrgResponseFromJSONTyped(json, false);
}

export function QzResponseOfListOrgResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfListOrgResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : QzResponseOfListOrgResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function QzResponseOfListOrgResponseToJSON(value?: QzResponseOfListOrgResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': QzResponseOfListOrgResponseDataToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

