/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { QzResponseOfLoginResponseData } from './QzResponseOfLoginResponseData';
import {
    QzResponseOfLoginResponseDataFromJSON,
    QzResponseOfLoginResponseDataFromJSONTyped,
    QzResponseOfLoginResponseDataToJSON,
} from './QzResponseOfLoginResponseData';

/**
 * 
 * @export
 * @interface QzResponseOfLoginResponse
 */
export interface QzResponseOfLoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof QzResponseOfLoginResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof QzResponseOfLoginResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {QzResponseOfLoginResponseData}
     * @memberof QzResponseOfLoginResponse
     */
    data?: QzResponseOfLoginResponseData;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfLoginResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfLoginResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the QzResponseOfLoginResponse interface.
 */
export function instanceOfQzResponseOfLoginResponse(value: object): boolean {
    return true;
}

export function QzResponseOfLoginResponseFromJSON(json: any): QzResponseOfLoginResponse {
    return QzResponseOfLoginResponseFromJSONTyped(json, false);
}

export function QzResponseOfLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfLoginResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : QzResponseOfLoginResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function QzResponseOfLoginResponseToJSON(value?: QzResponseOfLoginResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': QzResponseOfLoginResponseDataToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

