/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { QzResponseOfListMembersResponse2Data } from './QzResponseOfListMembersResponse2Data';
import {
    QzResponseOfListMembersResponse2DataFromJSON,
    QzResponseOfListMembersResponse2DataFromJSONTyped,
    QzResponseOfListMembersResponse2DataToJSON,
} from './QzResponseOfListMembersResponse2Data';

/**
 * 
 * @export
 * @interface QzResponseOfListMembersResponse2
 */
export interface QzResponseOfListMembersResponse2 {
    /**
     * 
     * @type {boolean}
     * @memberof QzResponseOfListMembersResponse2
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof QzResponseOfListMembersResponse2
     */
    code?: ErrorCode;
    /**
     * 
     * @type {QzResponseOfListMembersResponse2Data}
     * @memberof QzResponseOfListMembersResponse2
     */
    data?: QzResponseOfListMembersResponse2Data;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfListMembersResponse2
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfListMembersResponse2
     */
    traceId?: string;
}

/**
 * Check if a given object implements the QzResponseOfListMembersResponse2 interface.
 */
export function instanceOfQzResponseOfListMembersResponse2(value: object): boolean {
    return true;
}

export function QzResponseOfListMembersResponse2FromJSON(json: any): QzResponseOfListMembersResponse2 {
    return QzResponseOfListMembersResponse2FromJSONTyped(json, false);
}

export function QzResponseOfListMembersResponse2FromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfListMembersResponse2 {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : QzResponseOfListMembersResponse2DataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function QzResponseOfListMembersResponse2ToJSON(value?: QzResponseOfListMembersResponse2 | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': QzResponseOfListMembersResponse2DataToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

