/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { MyIssueResponse } from './MyIssueResponse';
import {
    instanceOfMyIssueResponse,
    MyIssueResponseFromJSON,
    MyIssueResponseFromJSONTyped,
    MyIssueResponseToJSON,
} from './MyIssueResponse';

/**
 * @type QzResponseOfMyIssueResponseData
 * 
 * @export
 */
export type QzResponseOfMyIssueResponseData = MyIssueResponse;

export function QzResponseOfMyIssueResponseDataFromJSON(json: any): QzResponseOfMyIssueResponseData {
    return QzResponseOfMyIssueResponseDataFromJSONTyped(json, false);
}

export function QzResponseOfMyIssueResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfMyIssueResponseData {
    if (json == null) {
        return json;
    }
    return MyIssueResponseFromJSONTyped(json, true);
}

export function QzResponseOfMyIssueResponseDataToJSON(value?: QzResponseOfMyIssueResponseData | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfMyIssueResponse(value)) {
        return MyIssueResponseToJSON(value as MyIssueResponse);
    }

    return {};
}

