/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { QzResponseOfMyIssueResponseData } from './QzResponseOfMyIssueResponseData';
import {
    QzResponseOfMyIssueResponseDataFromJSON,
    QzResponseOfMyIssueResponseDataFromJSONTyped,
    QzResponseOfMyIssueResponseDataToJSON,
} from './QzResponseOfMyIssueResponseData';

/**
 * 
 * @export
 * @interface QzResponseOfMyIssueResponse
 */
export interface QzResponseOfMyIssueResponse {
    /**
     * 
     * @type {boolean}
     * @memberof QzResponseOfMyIssueResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof QzResponseOfMyIssueResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {QzResponseOfMyIssueResponseData}
     * @memberof QzResponseOfMyIssueResponse
     */
    data?: QzResponseOfMyIssueResponseData;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfMyIssueResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfMyIssueResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the QzResponseOfMyIssueResponse interface.
 */
export function instanceOfQzResponseOfMyIssueResponse(value: object): boolean {
    return true;
}

export function QzResponseOfMyIssueResponseFromJSON(json: any): QzResponseOfMyIssueResponse {
    return QzResponseOfMyIssueResponseFromJSONTyped(json, false);
}

export function QzResponseOfMyIssueResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfMyIssueResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : QzResponseOfMyIssueResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function QzResponseOfMyIssueResponseToJSON(value?: QzResponseOfMyIssueResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': QzResponseOfMyIssueResponseDataToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

