/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * An ASP.NET Core Web API for managing ToDo items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { QzResponseOfAddTeamResponseData } from './QzResponseOfAddTeamResponseData';
import {
    QzResponseOfAddTeamResponseDataFromJSON,
    QzResponseOfAddTeamResponseDataFromJSONTyped,
    QzResponseOfAddTeamResponseDataToJSON,
} from './QzResponseOfAddTeamResponseData';

/**
 * 
 * @export
 * @interface QzResponseOfAddTeamResponse
 */
export interface QzResponseOfAddTeamResponse {
    /**
     * 
     * @type {boolean}
     * @memberof QzResponseOfAddTeamResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof QzResponseOfAddTeamResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {QzResponseOfAddTeamResponseData}
     * @memberof QzResponseOfAddTeamResponse
     */
    data?: QzResponseOfAddTeamResponseData;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfAddTeamResponse
     */
    message?: string;
    /**
     * 
     * @type {number}
     * @memberof QzResponseOfAddTeamResponse
     */
    message1?: number;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfAddTeamResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the QzResponseOfAddTeamResponse interface.
 */
export function instanceOfQzResponseOfAddTeamResponse(value: object): boolean {
    return true;
}

export function QzResponseOfAddTeamResponseFromJSON(json: any): QzResponseOfAddTeamResponse {
    return QzResponseOfAddTeamResponseFromJSONTyped(json, false);
}

export function QzResponseOfAddTeamResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfAddTeamResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : QzResponseOfAddTeamResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'message1': json['message1'] == null ? undefined : json['message1'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function QzResponseOfAddTeamResponseToJSON(value?: QzResponseOfAddTeamResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': QzResponseOfAddTeamResponseDataToJSON(value['data']),
        'message': value['message'],
        'message1': value['message1'],
        'traceId': value['traceId'],
    };
}

