/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { QzResponseOfListMembersResponseData } from './QzResponseOfListMembersResponseData';
import {
    QzResponseOfListMembersResponseDataFromJSON,
    QzResponseOfListMembersResponseDataFromJSONTyped,
    QzResponseOfListMembersResponseDataToJSON,
} from './QzResponseOfListMembersResponseData';

/**
 * 
 * @export
 * @interface QzResponseOfListMembersResponse
 */
export interface QzResponseOfListMembersResponse {
    /**
     * 
     * @type {boolean}
     * @memberof QzResponseOfListMembersResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof QzResponseOfListMembersResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {QzResponseOfListMembersResponseData}
     * @memberof QzResponseOfListMembersResponse
     */
    data?: QzResponseOfListMembersResponseData;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfListMembersResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof QzResponseOfListMembersResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the QzResponseOfListMembersResponse interface.
 */
export function instanceOfQzResponseOfListMembersResponse(value: object): boolean {
    return true;
}

export function QzResponseOfListMembersResponseFromJSON(json: any): QzResponseOfListMembersResponse {
    return QzResponseOfListMembersResponseFromJSONTyped(json, false);
}

export function QzResponseOfListMembersResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QzResponseOfListMembersResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : QzResponseOfListMembersResponseDataFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function QzResponseOfListMembersResponseToJSON(value?: QzResponseOfListMembersResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': QzResponseOfListMembersResponseDataToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

