/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ErrorCode } from './ErrorCode';
import {
    ErrorCodeFromJSON,
    ErrorCodeFromJSONTyped,
    ErrorCodeToJSON,
} from './ErrorCode';
import type { TodoItemResponse } from './TodoItemResponse';
import {
    TodoItemResponseFromJSON,
    TodoItemResponseFromJSONTyped,
    TodoItemResponseToJSON,
} from './TodoItemResponse';

/**
 * 
 * @export
 * @interface TodoItemResponseQzResponse
 */
export interface TodoItemResponseQzResponse {
    /**
     * 
     * @type {boolean}
     * @memberof TodoItemResponseQzResponse
     */
    success?: boolean;
    /**
     * 
     * @type {ErrorCode}
     * @memberof TodoItemResponseQzResponse
     */
    code?: ErrorCode;
    /**
     * 
     * @type {TodoItemResponse}
     * @memberof TodoItemResponseQzResponse
     */
    data?: TodoItemResponse;
    /**
     * 
     * @type {string}
     * @memberof TodoItemResponseQzResponse
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof TodoItemResponseQzResponse
     */
    traceId?: string;
}

/**
 * Check if a given object implements the TodoItemResponseQzResponse interface.
 */
export function instanceOfTodoItemResponseQzResponse(value: object): boolean {
    return true;
}

export function TodoItemResponseQzResponseFromJSON(json: any): TodoItemResponseQzResponse {
    return TodoItemResponseQzResponseFromJSONTyped(json, false);
}

export function TodoItemResponseQzResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItemResponseQzResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'] == null ? undefined : json['success'],
        'code': json['code'] == null ? undefined : ErrorCodeFromJSON(json['code']),
        'data': json['data'] == null ? undefined : TodoItemResponseFromJSON(json['data']),
        'message': json['message'] == null ? undefined : json['message'],
        'traceId': json['traceId'] == null ? undefined : json['traceId'],
    };
}

export function TodoItemResponseQzResponseToJSON(value?: TodoItemResponseQzResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'code': ErrorCodeToJSON(value['code']),
        'data': TodoItemResponseToJSON(value['data']),
        'message': value['message'],
        'traceId': value['traceId'],
    };
}

