/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TodoDto } from './TodoDto';
import {
    TodoDtoFromJSON,
    TodoDtoFromJSONTyped,
    TodoDtoToJSON,
} from './TodoDto';

/**
 * 
 * @export
 * @interface TodoItemResponse
 */
export interface TodoItemResponse {
    /**
     * 
     * @type {TodoDto}
     * @memberof TodoItemResponse
     */
    todoInfo?: TodoDto;
}

/**
 * Check if a given object implements the TodoItemResponse interface.
 */
export function instanceOfTodoItemResponse(value: object): boolean {
    return true;
}

export function TodoItemResponseFromJSON(json: any): TodoItemResponse {
    return TodoItemResponseFromJSONTyped(json, false);
}

export function TodoItemResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): TodoItemResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'todoInfo': json['todoInfo'] == null ? undefined : TodoDtoFromJSON(json['todoInfo']),
    };
}

export function TodoItemResponseToJSON(value?: TodoItemResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'todoInfo': TodoDtoToJSON(value['todoInfo']),
    };
}

