/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Workitem
 */
export interface Workitem {
    /**
     * 
     * @type {string}
     * @memberof Workitem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof Workitem
     */
    orgId?: string;
    /**
     * 
     * @type {string}
     * @memberof Workitem
     */
    projectId?: string;
    /**
     * 
     * @type {string}
     * @memberof Workitem
     */
    issueType?: string;
    /**
     * 
     * @type {string}
     * @memberof Workitem
     */
    issueTitle?: string;
    /**
     * 
     * @type {string}
     * @memberof Workitem
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof Workitem
     */
    createdBy?: string;
}

/**
 * Check if a given object implements the Workitem interface.
 */
export function instanceOfWorkitem(value: object): boolean {
    return true;
}

export function WorkitemFromJSON(json: any): Workitem {
    return WorkitemFromJSONTyped(json, false);
}

export function WorkitemFromJSONTyped(json: any, ignoreDiscriminator: boolean): Workitem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'orgId': json['orgId'] == null ? undefined : json['orgId'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'issueType': json['issueType'] == null ? undefined : json['issueType'],
        'issueTitle': json['issueTitle'] == null ? undefined : json['issueTitle'],
        'createdAt': json['createdAt'] == null ? undefined : json['createdAt'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
    };
}

export function WorkitemToJSON(value?: Workitem | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'orgId': value['orgId'],
        'projectId': value['projectId'],
        'issueType': value['issueType'],
        'issueTitle': value['issueTitle'],
        'createdAt': value['createdAt'],
        'createdBy': value['createdBy'],
    };
}

