/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * An ASP.NET Core Web API for managing ToDo items
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QzResponseOfMyIssueResponse,
} from '../models/index';
import {
    QzResponseOfMyIssueResponseFromJSON,
    QzResponseOfMyIssueResponseToJSON,
} from '../models/index';

export interface IssueMyIssueRequest {
    orgId?: number;
}

/**
 * 
 */
export class IssueApi extends runtime.BaseAPI {

    /**
     */
    async issueMyIssueRaw(requestParameters: IssueMyIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QzResponseOfMyIssueResponse>> {
        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/collab/Issue/MyIssue`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QzResponseOfMyIssueResponseFromJSON(jsonValue));
    }

    /**
     */
    async issueMyIssue(requestParameters: IssueMyIssueRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QzResponseOfMyIssueResponse> {
        const response = await this.issueMyIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
