/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QzResponseOfListMembersResponse,
  QzResponseOfMemberResponse,
} from '../models/index';
import {
    QzResponseOfListMembersResponseFromJSON,
    QzResponseOfListMembersResponseToJSON,
    QzResponseOfMemberResponseFromJSON,
    QzResponseOfMemberResponseToJSON,
} from '../models/index';

export interface MembersListMembersRequest {
    organizationId: number;
}

export interface MembersMemberRequest {
    organizationId: number;
    accountId: number;
}

/**
 * 
 */
export class MembersApi extends runtime.BaseAPI {

    /**
     */
    async membersListMembersRaw(requestParameters: MembersListMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QzResponseOfListMembersResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling membersListMembers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Organization/{organizationId}/Members`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QzResponseOfListMembersResponseFromJSON(jsonValue));
    }

    /**
     */
    async membersListMembers(requestParameters: MembersListMembersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QzResponseOfListMembersResponse> {
        const response = await this.membersListMembersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async membersMemberRaw(requestParameters: MembersMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QzResponseOfMemberResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling membersMember().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling membersMember().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Organization/{organizationId}/Members/{accountId}`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QzResponseOfMemberResponseFromJSON(jsonValue));
    }

    /**
     */
    async membersMember(requestParameters: MembersMemberRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QzResponseOfMemberResponse> {
        const response = await this.membersMemberRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
