/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ListMembersResponseQzResponse,
  MemberResponseQzResponse,
} from '../models/index';
import {
    ListMembersResponseQzResponseFromJSON,
    ListMembersResponseQzResponseToJSON,
    MemberResponseQzResponseFromJSON,
    MemberResponseQzResponseToJSON,
} from '../models/index';

export interface ApiOrganizationOrganizationIdMembersAccountIdGetRequest {
    organizationId: string;
    accountId: string;
}

export interface ApiOrganizationOrganizationIdMembersGetRequest {
    organizationId: string;
}

/**
 * 
 */
export class MembersApi extends runtime.BaseAPI {

    /**
     */
    async apiOrganizationOrganizationIdMembersAccountIdGetRaw(requestParameters: ApiOrganizationOrganizationIdMembersAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MemberResponseQzResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling apiOrganizationOrganizationIdMembersAccountIdGet().'
            );
        }

        if (requestParameters['accountId'] == null) {
            throw new runtime.RequiredError(
                'accountId',
                'Required parameter "accountId" was null or undefined when calling apiOrganizationOrganizationIdMembersAccountIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Organization/{organizationId}/Members/{accountId}`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))).replace(`{${"accountId"}}`, encodeURIComponent(String(requestParameters['accountId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MemberResponseQzResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiOrganizationOrganizationIdMembersAccountIdGet(requestParameters: ApiOrganizationOrganizationIdMembersAccountIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MemberResponseQzResponse> {
        const response = await this.apiOrganizationOrganizationIdMembersAccountIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiOrganizationOrganizationIdMembersGetRaw(requestParameters: ApiOrganizationOrganizationIdMembersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ListMembersResponseQzResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling apiOrganizationOrganizationIdMembersGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Organization/{organizationId}/Members`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ListMembersResponseQzResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiOrganizationOrganizationIdMembersGet(requestParameters: ApiOrganizationOrganizationIdMembersGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ListMembersResponseQzResponse> {
        const response = await this.apiOrganizationOrganizationIdMembersGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
