/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  StringQzResponse,
  TodoDto,
  TodoItemResponseQzResponse,
} from '../models/index';
import {
    StringQzResponseFromJSON,
    StringQzResponseToJSON,
    TodoDtoFromJSON,
    TodoDtoToJSON,
    TodoItemResponseQzResponseFromJSON,
    TodoItemResponseQzResponseToJSON,
} from '../models/index';

export interface DeleteRequest {
    id?: string;
}

export interface GetRequest {
    id?: string;
}

export interface PostRequest {
    todoDto?: TodoDto;
}

export interface PutRequest {
    todoDto?: TodoDto;
}

/**
 * 
 */
export class TodoItemApi extends runtime.BaseAPI {

    /**
     */
    async _deleteRaw(requestParameters: DeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringQzResponse>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['Id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/TodoItem/Delete`,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringQzResponseFromJSON(jsonValue));
    }

    /**
     */
    async _delete(requestParameters: DeleteRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringQzResponse> {
        const response = await this._deleteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getRaw(requestParameters: GetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<TodoItemResponseQzResponse>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['Id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/TodoItem/Get`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TodoItemResponseQzResponseFromJSON(jsonValue));
    }

    /**
     */
    async get(requestParameters: GetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TodoItemResponseQzResponse> {
        const response = await this.getRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async postRaw(requestParameters: PostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringQzResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/TodoItem/Post`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: TodoDtoToJSON(requestParameters['todoDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringQzResponseFromJSON(jsonValue));
    }

    /**
     */
    async post(requestParameters: PostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringQzResponse> {
        const response = await this.postRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async putRaw(requestParameters: PutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<StringQzResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/TodoItem/Put`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: TodoDtoToJSON(requestParameters['todoDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => StringQzResponseFromJSON(jsonValue));
    }

    /**
     */
    async put(requestParameters: PutRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<StringQzResponse> {
        const response = await this.putRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
