/* tslint:disable */
/* eslint-disable */
/**
 * Qz.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MyIssueResponseQzResponse,
} from '../models/index';
import {
    MyIssueResponseQzResponseFromJSON,
    MyIssueResponseQzResponseToJSON,
} from '../models/index';

export interface ApiOrganizationOrganizationIdWorkitemsMyIssueGetRequest {
    organizationId: string;
}

/**
 * 
 */
export class WorkitemsApi extends runtime.BaseAPI {

    /**
     */
    async apiOrganizationOrganizationIdWorkitemsMyIssueGetRaw(requestParameters: ApiOrganizationOrganizationIdWorkitemsMyIssueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MyIssueResponseQzResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling apiOrganizationOrganizationIdWorkitemsMyIssueGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Organization/{organizationId}/Workitems/MyIssue`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MyIssueResponseQzResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiOrganizationOrganizationIdWorkitemsMyIssueGet(requestParameters: ApiOrganizationOrganizationIdWorkitemsMyIssueGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MyIssueResponseQzResponse> {
        const response = await this.apiOrganizationOrganizationIdWorkitemsMyIssueGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
