/* tslint:disable */
/* eslint-disable */
/**
 * 轻舟 RestAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  QzResponseOfMyIssueResponse,
} from '../models/index';
import {
    QzResponseOfMyIssueResponseFromJSON,
    QzResponseOfMyIssueResponseToJSON,
} from '../models/index';

export interface WorkitemsMyIssueRequest {
    organizationId: string;
    orgId?: number;
}

/**
 * 
 */
export class WorkitemsApi extends runtime.BaseAPI {

    /**
     */
    async workitemsMyIssueRaw(requestParameters: WorkitemsMyIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<QzResponseOfMyIssueResponse>> {
        if (requestParameters['organizationId'] == null) {
            throw new runtime.RequiredError(
                'organizationId',
                'Required parameter "organizationId" was null or undefined when calling workitemsMyIssue().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['orgId'] != null) {
            queryParameters['orgId'] = requestParameters['orgId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/Organization/{organizationId}/Workitems/MyIssue`.replace(`{${"organizationId"}}`, encodeURIComponent(String(requestParameters['organizationId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => QzResponseOfMyIssueResponseFromJSON(jsonValue));
    }

    /**
     */
    async workitemsMyIssue(requestParameters: WorkitemsMyIssueRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<QzResponseOfMyIssueResponse> {
        const response = await this.workitemsMyIssueRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
